[FIX] website_sale: set default model when creating mail template from settings
Currently, an error occurs when the scheduled action
`Payment: Post-process transactions` attempts to post-process a
payment after performing the following steps:

- Install `website_sale` with demo data
- Enable payment provider `Demo` for testing
- Go to Settings and search for `Order Confirmation`
- Under Email, enter a template name that does not exist (e.g., `Test`)
- Click `Create "Test"` and save the settings
- Go to the website shop, place an order, and complete the payment

Error: `KeyError: False`

Error when user selects `model_id(Applies_to)` as `journal_entry` in the
above `Test` template:
```
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: account.move(1,), User: 1)
```

The issue occurs because clicks `Create "Test"` creates a `mail.template` record
without setting the required `model_id` field. As a result, `render_model`
remains empty, causing an error when `self.env[self.render_model]` is
accessed (see code [1] and [2]).

This commit fixes the above issue by setting `default_model` to `sale.order`
in the context, ensuring the correct model is set when a user creates an
`Order Confirmation` email template. The same change is also applied to
the invoice and rating email templates to ensure the appropriate model is
provided when creating each template.

[1]: https://github.com/odoo/odoo/blob/bb94f13b38f0bf1ce8886f4630ad42caf6c56325/addons/mail/models/mail_render_mixin.py#L739
[2]: https://github.com/odoo/odoo/blob/bb94f13b38f0bf1ce8886f4630ad42caf6c56325/addons/mail/models/mail_template.py#L125-L128

Sentry-7634490774,7635560002

closes odoo/odoo#286490

Signed-off-by: ANSARI MAHAMADASIF (maan) <maan@odoo.com>